iio: adc: adm1177: Fix compilation with CONFIG_ADM1177=m
This fixes:

	In file included from include/linux/device/driver.h:21,
			 from include/linux/device.h:32,
			 from drivers/iio/adc/adm1177.c:9:
	drivers/iio/adc/adm1177.c:222:25: error: ‘nau7802_dt_ids’ undeclared here (not in a function)
	  222 | MODULE_DEVICE_TABLE(of, nau7802_dt_ids);
	      |                         ^~~~~~~~~~~~~~
	include/linux/module.h:243:15: note: in definition of macro ‘MODULE_DEVICE_TABLE’
	  243 | extern typeof(name) __mod_##type##__##name##_device_table               \
	      |               ^~~~
	include/linux/module.h:243:21: error: ‘__mod_of__nau7802_dt_ids_device_table’ aliased to undefined symbol ‘nau7802_dt_ids’
	  243 | extern typeof(name) __mod_##type##__##name##_device_table               \
	      |                     ^~~~~~
	drivers/iio/adc/adm1177.c:222:1: note: in expansion of macro ‘MODULE_DEVICE_TABLE’
	  222 | MODULE_DEVICE_TABLE(of, nau7802_dt_ids);
	      | ^~~~~~~~~~~~~~~~~~~

Should I try to guess which driver was used as a template for the
adm1177 one?

Fixes: dc2f40afb221 ("iio: Add ADM1177 Hot Swap Controller and Digital Power Monitor driver")
Signed-off-by: Uwe Kleine-König <u.kleine-koenig@baylibre.com>
(cherry picked from commit 259486c8aaf0e3047aed2a91fbcdf70d1b294094)