dt-bindings: iio: frequency: adf4371 fix allOf node not an array
The adf4371.yaml schema was broken because it doesn't use an array for
an allOf: node which caused the bindings checker to crash with the
following error:

    Traceback (most recent call last):
    File "/home/david/.local/bin/dt-mk-schema", line 38, in <module>
        schemas = dtschema.DTValidator(args.schemas).schemas
    File "/home/david/.local/pipx/venvs/dtschema/lib/python3.10/site-packages/dtschema/validator.py", line 359, in __init__
        self.schemas = process_schemas(schema_files)
    File "/home/david/.local/pipx/venvs/dtschema/lib/python3.10/site-packages/dtschema/validator.py", line 276, in process_schemas
        sch = process_schema(os.path.abspath(filename))
    File "/home/david/.local/pipx/venvs/dtschema/lib/python3.10/site-packages/dtschema/validator.py", line 260, in process_schema
        schema = dtsch.fixup()
    File "/home/david/.local/pipx/venvs/dtschema/lib/python3.10/site-packages/dtschema/schema.py", line 151, in fixup
        dtschema.fixups.fixup_schema(processed_schema)
    File "/home/david/.local/pipx/venvs/dtschema/lib/python3.10/site-packages/dtschema/fixups.py", line 483, in fixup_schema
        fixup_sub_schema(schema)
    File "/home/david/.local/pipx/venvs/dtschema/lib/python3.10/site-packages/dtschema/fixups.py", line 368, in fixup_sub_schema
        walk_properties(prop, v[prop])
    File "/home/david/.local/pipx/venvs/dtschema/lib/python3.10/site-packages/dtschema/fixups.py", line 296, in walk_properties
        fixup_vals(propname, schema)
    File "/home/david/.local/pipx/venvs/dtschema/lib/python3.10/site-packages/dtschema/fixups.py", line 273, in fixup_vals
        _fixup_int_array_min_max_to_matrix(propname, schema)
    File "/home/david/.local/pipx/venvs/dtschema/lib/python3.10/site-packages/dtschema/fixups.py", line 112, in _fixup_int_array_min_max_to_matrix
        if not is_int_array_schema(propname, subschema):
    File "/home/david/.local/pipx/venvs/dtschema/lib/python3.10/site-packages/dtschema/fixups.py", line 98, in is_int_array_schema
        return int_array_re.search(item['$ref'])
    TypeError: string indices must be integers

This was causing `make dt_binding_check` to always fail because of the
crash.

Fixes: 67d89797e6b7 ("Merge tag 'xilinx-v2021.1' of https://github.com/Xilinx/linux-xlnx.git")
Signed-off-by: David Lechner <dlechner@baylibre.com>
(cherry picked from commit b7d1346333f0b914828454d4bf7ab5edca33b41b)